[package]
name = "mbs4-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
axum.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
http = "1.2.0"
mbs4-types = { path = "../mbs4-types" }
mbs4-auth = { path = "../mbs4-auth" }
time = "0.3.37"
tower-sessions = "0.14.0"
url = "2.5.4"
sqlx.workspace = true
serde_json.workspace = true
argon2 = { version = "0.5.3", features = ["std"] }
thiserror = "2.0.11"
futures = "0.3.31"
cookie = "0.18.1"
tower-cookies = "0.11.0"

[profile.dev.package.sqlx-macros]
opt-level = 3
