name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@v4
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/master' }}
    - name: Check formating
      run: cargo fmt --all --check
    - name: Check compilation
      run: cargo check --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
